server:
  port: 8761
spring:
  application:
    name: eureka-registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
#    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: true